const projects = [
  {
    id: 1,
    img: "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=800&q=80",
    alt: "Legacy Solar website",
    tag: "Solar Energy · 2026",
    title: "Legacy Solar",
    desc: "Professional solar energy company website with modern UI and strong conversion focus.",
    tech: ["HTML/CSS", "JavaScript", "Responsive"],
    url: "https://legacysolar.in",
  },
  {
    id: 2,
    img: "https://images.unsplash.com/photo-1550345332-09e3ac987658?w=800&q=80",
    alt: "Star Fitness Studio website",
    tag: "Fitness · 2026",
    title: "Star Fitness Studio",
    desc: "High-energy fitness studio site built to attract members and showcase classes beautifully.",
    tech: ["Web Design", "UI/UX", "Mobile-first"],
    url: "https://starfitnessstudio.in",
  },
  {
    id: 3,
    img: "https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=800&q=80",
    alt: "WafflesHub website",
    tag: "Food & Lifestyle · 2026",
    title: "WafflesHub",
    desc: "Modern food brand website with a clean, appetizing design built to attract customers and drive orders.",
    tech: ["Web Design", "UI/UX", "Responsive"],
    url: "https://waffleshub.com/",
  },
  {
    id: 4,
    img: "https://images.unsplash.com/photo-1555597673-b21d5c935865?w=800&q=80",
    alt: "Unbent Martial Fitness website",
    tag: "Martial Arts · 2026",
    title: "Unbent Martial Fitness",
    desc: "Bold, high-energy website for a martial arts fitness brand — built to inspire action and drive sign-ups.",
    tech: ["Web Design", "UI/UX", "Responsive"],
    url: "https://unbentmartialfitness.com",
  },
  {
    id: 5,
    img: "https://images.unsplash.com/photo-1611926653458-09294b3142bf?w=800&q=80",
    alt: "DigitalWithChirag website",
    tag: "Digital Marketing · 2026",
    title: "DigitalWithChirag",
    desc: "Personal brand website for a digital marketer — designed to build authority, attract clients and convert visitors.",
    tech: ["Web Design", "Personal Brand", "Responsive"],
    url: "https://www.digitalwithchirag.com/",
  },
  {
    id: 6,
    img: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80",
    alt: "Siolim Cafe website",
    tag: "Cafe & Dining · 2026",
    title: "Siolim Cafe",
    desc: "Warm and inviting cafe website designed to showcase the menu, ambiance and drive footfall.",
    tech: ["Web Design", "UI/UX", "Responsive"],
    url: "https://siolimcafe.vercel.app/",
  },
];