import { useEffect, useRef } from "react";

const cards = [
  {
    number: "01",
    tag: "First Impressions",
    headline: "Your website is open 24/7 — even when you're asleep.",
    body: "Before a client calls you, emails you, or walks through your door — they Google you. If they find nothing, or something outdated, they move on. A sharp, modern website tells them instantly: this person is serious, professional, and worth their money.",
    stat: "75%",
    statLabel: "of users judge credibility based on website design alone.",
    accent: "#facc15",
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none">
        <circle cx="12" cy="12" r="10" stroke="#facc15" strokeWidth="1.5"/>
        <path d="M12 6v6l4 2" stroke="#facc15" strokeWidth="1.5" strokeLinecap="round"/>
      </svg>
    ),
  },
  {
    number: "02",
    tag: "Trust & Credibility",
    headline: "People buy from businesses they trust. Your website builds that trust.",
    body: "A well-designed website signals that you're established, reliable, and professional. It's your digital storefront — and just like a physical store, if it looks polished, people feel safe handing over their money. No website? Clients assume you're just a side hustle.",
    stat: "81%",
    statLabel: "of shoppers research a business online before making a purchase.",
    accent: "#818cf8",
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none">
        <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" stroke="#818cf8" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
      </svg>
    ),
  },
  {
    number: "03",
    tag: "More Leads, More Sales",
    headline: "A website that works while you work — generating leads on autopilot.",
    body: "Your website isn't just a brochure. Done right, it's a lead-generating machine — capturing enquiries, showcasing your work, answering FAQs, and nudging visitors to contact you. Every day without one is revenue you're leaving on the table.",
    stat: "3.5x",
    statLabel: "more leads generated by businesses with a strong online presence.",
    accent: "#34d399",
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none">
        <polyline points="22 7 13.5 15.5 8.5 10.5 2 17" stroke="#34d399" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
        <polyline points="16 7 22 7 22 13" stroke="#34d399" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
      </svg>
    ),
  },
  {
    number: "04",
    tag: "Beat Your Competition",
    headline: "Your competitors already have a website. Don't let them win by default.",
    body: "Every day a potential customer searches for what you offer — and finds your competitor instead of you. A high-quality website puts you in the game and a great one puts you ahead. Design, speed, and strategy are the difference between being found and being invisible.",
    stat: "50%",
    statLabel: "of small businesses without a website lose customers to competitors who have one.",
    accent: "#f472b6",
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none">
        <path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z" stroke="#f472b6" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
      </svg>
    ),
  },
  {
    number: "05",
    tag: "Scale Without Limits",
    headline: "A great website grows with your business — no extra staff needed.",
    body: "Hiring more people to handle enquiries, bookings, and customer questions costs a fortune. Your website can do all of that automatically — 24 hours a day, 365 days a year. It's the highest-ROI investment any business can make in their growth.",
    stat: "↑ ROI",
    statLabel: "Websites consistently deliver the highest return on investment of any marketing channel.",
    accent: "#fb923c",
    icon: (
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none">
        <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" stroke="#fb923c" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
      </svg>
    ),
  },
];

export default function WhyWebsite({ setPage }) {
  const sectionRef = useRef(null);

  useEffect(() => {
    const cards = sectionRef.current?.querySelectorAll(".ww-card");
    if (!cards) return;
    const io = new IntersectionObserver(
      (entries) => entries.forEach((e) => {
        if (e.isIntersecting) e.target.classList.add("ww-visible");
      }),
      { threshold: 0.15 }
    );
    cards.forEach((c) => io.observe(c));
    return () => io.disconnect();
  }, []);

  return (
    <section className="ww-section" ref={sectionRef}>
      <div className="wrap">
        <div className="ww-header">
          <span className="tag">Why It Matters</span>
          <h2 className="sec-h">Why every business <em>needs</em> a website</h2>
          <p className="muted">The hard truths that turn browsers into buyers.</p>
        </div>

        <div className="ww-stack">
          {cards.map((card, i) => (
            <div
              className="ww-card"
              key={card.number}
              style={{ "--accent": card.accent, "--delay": `${i * 0.1}s`, top: `${90 + i * 22}px` }}
            >
              <div className="ww-card-inner">
                <div className="ww-left">
                  <div className="ww-icon">{card.icon}</div>
                  <div className="ww-num">{card.number}</div>
                </div>
                <div className="ww-body">
                  <span className="ww-tag">{card.tag}</span>
                  <h3 className="ww-headline">{card.headline}</h3>
                  <p className="ww-text">{card.body}</p>
                  <div className="ww-stat">
                    <span className="ww-stat-num">{card.stat}</span>
                    <span className="ww-stat-label">{card.statLabel}</span>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="ww-cta">
          <p>Ready to give your business the online presence it deserves?</p>
          <button className="btn btn-gold" onClick={() => setPage("contact")}>
            Let's Build Your Website
            <svg width="15" height="15" viewBox="0 0 16 16" fill="none">
              <path d="M3 8h10M9 4l4 4-4 4" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          </button>
        </div>
      </div>
    </section>
  );
}